---

AWSTemplateFormatVersion: '2010-09-09'

Description: 'Basic CloudFormation template to create an S3 bucket'

Parameters:
  BucketBaseName:
    Type: String
    Default: subhamay-test-bucket
    Description: Base name for the S3 bucket (account ID and region will be appended)

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketBaseName}-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs:
  S3BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref S3Bucket
  S3BucketArn:
    Description: "ARN of the S3 bucket"
    Value: !GetAtt S3Bucket.Arn
  