name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/deploy.yaml'
    # Allowed environment values: ci, devl, test, prod
    # To deploy to a different environment, update the hardcoded value in the job

jobs:
  deploy:
    uses: subhamay-bhattacharyya-gha/cloudformation-deploy-wf/.github/workflows/cfn-deploy.yaml@feature/GHA-0003-initial-release-cloudform
    with:
      environment: devl
      aws-region: ${{ vars.AWS_REGION }}
      aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
      oidc-role-name: ${{ vars.OIDC_ROLE_NAME }}
      cfn-templates-s3-bucket: ${{ vars.CFN_TEMPLATES_S3_BUCKET }}
      stack-name: ${{ github.event.repository.name }}
      template-file: infra/template.yaml
      parameters-file: infra/parameters.json
